name: "Env setup"
description: "Node.js, bun & pnpm setup"
inputs:
  node-version:
    description: "The version of Node.js"
    required: true
    default: "20.x"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - uses: oven-sh/setup-bun@v1
      name: Install bun
      with:
        bun-version: "latest"
    - run: bun install
      shell: bash
